export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const GET_AUTH_USER = "GET_AUTH_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";

export const ADD_AVATAR = "ADD_AVATAR";
export const REMOVE_AVATAR = "REMOVE_AVATAR";

export const ADD_PROFILE_BIO = "ADD_PROFILE_BIO";
export const EDIT_PROFILE_BIO = "EDIT_PROFILE_BIO";

export const ADD_SOCIAL_LINK = "ADD_SOCIAL_LINK";
export const REMOVE_SOCIAL_LINK = "REMOVE_SOCIAL_LINK";
export const EDIT_SOCIAL_LINK = "EDIT_SOCIAL_LINK";

export const ADD_OTHER_LINK = "ADD_OTHER_LINK";
export const REMOVE_OTHER_LINK = "REMOVER_OTHER_LINK";
export const EDIT_OTHER_LINK = "EDIT_OTHER_LINK";
